### ISSUE TITLE
Make sure everyone saw the security notice

### ISSUE THREAD

**Issue by grahamc** [nix-community/aarch64-build-box#11]
I updated the security notice at https://github.com/nix-community/aarch64-build-box#notes-on-security-and-safety, let's make sure everyone with access sees it.

 - [x] @andir
 - [x] @dezgeg
 - [x] @dhess
 - [x] @flokli
 - [x] @globin
 - [x] @grahamc
 - [x] @jtojnar
 - [x] @kamilchm
 - [x] @lheckemann
 - [x] @moretea
 - [x] @vcunat
 - [x] @yegortimoshenko

**Comment by yegortimoshenko** [comment]
Sure! (I only plan to use this builder via SSH anyway for the time being).

**Comment by dhess** [comment]
Good point.

**Comment by moretea** [comment]
Thanks @grahamc. Noted!

**Comment by vcunat** [comment]
> Good point. Can remote builds be container-ized?

Like every user having an independent nix store?  That seems doable, though probably not worth the human-time investment, considering the purpose of the machine (as perceived by me).

**Comment by kamilchm** [comment]
aknowledged

**Comment by grahamc** [comment]
Thanks everyone!
