### ISSUE TITLE
Update nixpkgs to fix Nix's /bin/sh

### ISSUE THREAD

**Issue by cstrahan** [nix-community/aarch64-build-box#17]
I was trying to build a Linux kernel and I ran into this failure:

    manual-config configurePhase buildRoot=/build/source/build pwd=/build/source
    '/build/source/build/.config' -> '/nix/store/wajbysr2cxiszvwh3rlk9rvqndkgsjlq-linux-config-4.4.115'
    make[1]: Entering directory '/build/source/build'
    /bin/sh: syntax error: support for $((arith)) is disabled

The problem is that Nix's `/bin/sh` isn't compiled with arithmetic expression support (along with a few other things). This was fixed in https://github.com/NixOS/nixpkgs/pull/34628 and https://github.com/NixOS/nixpkgs/pull/34677.

Could we bump the nixpkgs version to get these fixes, please? (Or, at the least, backport the first patch)

**Comment by grahamc** [comment]
Done, thanks.
