### ISSUE TITLE
MacOS Mojave entering no password restults in this

### ISSUE THREAD

**Issue by bryanbridges** [nix-community/aarch64-build-box#26]
Bryans-MacBook-Air:aarch64-build-box b$ sudo su
Password:
sh-3.2# ssh Bryans-MacBook-Air@aarch64.nixos.commnity -i /root/a-private-key
Warning: Identity file /root/a-private-key not accessible: No such file or directory.
ssh: Could not resolve hostname aarch64.nixos.commnity: nodename nor servname provided, or not known
sh-3.2# ssh ~b@aarch64.nixos.commnity -i /root/a-private-key
Warning: Identity file /root/a-private-key not accessible: No such file or directory.
ssh: Could not resolve hostname aarch64.nixos.commnity: nodename nor servname provided, or not known
sh-3.2# ssh Bryans-MacBook-Air.local@aarch64.nixos.community -i /root/a-private-key
Warning: Identity file /root/a-private-key not accessible: No such file or directory.
The authenticity of host 'aarch64.nixos.community (147.75.79.198)' can't be established.
ED25519 key fingerprint is SHA256:iPNPF+wdJezn9hz9tn02ONpwALemteTvq5Nz5xdsNa8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'aarch64.nixos.community,147.75.79.198' (ED25519) to the list of known hosts.
Password: 
Password: 
Password: 
Bryans-MacBook-Air.local@aarch64.nixos.community's password: 
Permission denied, please try again.
Bryans-MacBook-Air.local@aarch64.nixos.community's password: 
Permission denied, please try again.
Bryans-MacBook-Air.local@aarch64.nixos.community's password: 
Received disconnect from 147.75.79.198 port 22:2: Too many authentication failures
Disconnected from 147.75.79.198 port 22
sh-3.2# ssh Bryans-MacBook-Air.local@aarch64.nixos.community -i /root/a-private-key
Warning: Identity file /root/a-private-key not accessible: No such file or directory.
Password: 
Password: 
Password: 
Bryans-MacBook-Air.local@aarch64.nixos.community's password: 
Permission denied, please try again.
Bryans-MacBook-Air.local@aarch64.nixos.community's password: 
Permission denied, please try again.
Bryans-MacBook-Air.local@aarch64.nixos.community's password: 
Received disconnect from 147.75.79.198 port 22:2: Too many authentication failures
Disconnected from 147.75.79.198 port 22
sh-3.2#

**Comment by grahamc** [comment]
Hey Bryan,

In order to use the build box you have to send a PR adding your account. The build box's configuration is in this repo, but cloning it is not very useful.

The errors you see are due to not having an account registered on the server.

Graham
