### ISSUE TITLE
root partition is full

### ISSUE THREAD

**Issue by volth** [nix-community/aarch64-build-box#54]
..which often results in the builds failed with "No space left on device" ([example](https://logs.nix.ci/?attempt_id=97b99940-f4c8-48a5-acee-f90da26c0598&key=nixos%2Fnixpkgs.60261))
/ is 64GB tmpfs which seems quite big.
Perhaps, someone's home directory is full of files (I have no access to verify it)

**Comment by flokli** [comment]
Users homedirs are not persistent, and lost across reboots.

As the aarch64 build box currently has an uptime of 5 days, this bug likely doesn't apply anymore - we could discuss about using some of the storage attached to these boxes in an ephemeral fashion, but this should then be in another actionable issue.

**Comment by volth** [comment]
Yes, the exact issue doesn't apply.
But it could be a starting point to develop a solution which would prevent it in the future (for example cron script which checks free space and performs reboot)

**Comment by flokli** [comment]
@grahamc any opinions?

**Comment by grahamc** [comment]
Reboot on a "is it full?" cron seems fine :)

https://status.nixos.org/grafana/d/5LANB9pZk/per-instance-metrics?orgId=1&refresh=30s&var-instance=bd949fc7.packethost.net&from=1569700800000&to=now&fullscreen&panelId=6

**Comment by volth** [comment]
the root partition is "normally" 60% full (it is interesting why) and the remaining space in not enough to build `chromium` https://github.com/NixOS/nixpkgs/pull/66438/checks?check_run_id=273685593

Having `/` on `tmpfs` is good for SSD livetime but that limits the available disk space to the values which prevent using the server as the builder.

Of course it is possible to change the derivation to make it more space-savvy (using bunch of `lndir` in `unpackPhase` instead of default `cp -r`), but it will make the code in `nixpkgs` less readable and maintainable so I do not think it is the desired way to solve the builder's disk space issue.
